INSERT INTO teams (id, name, slug, logo_url) VALUES
('team-palmeiras', 'Palmeiras', 'palmeiras', 'https://upload.wikimedia.org/wikipedia/commons/1/10/Palmeiras_logo.svg'),
('team-bahia', 'Bahia', 'bahia', 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Escudo_do_Bahia.svg'),
('team-corinthians', 'Corinthians', 'corinthians', 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Corinthians_simbolo.svg'),
('team-sao-paulo', 'S?o Paulo', 'sao-paulo', 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Sao_Paulo_FC_logo.svg'),
('team-vasco', 'Vasco', 'vasco', 'https://upload.wikimedia.org/wikipedia/commons/1/18/CR_Vasco_da_Gama.svg');

INSERT INTO players (id, team_id, name, shirt_number, position) VALUES
('palmeiras-1', 'team-palmeiras', 'Weverton', 12, 'GOL'),
('palmeiras-2', 'team-palmeiras', 'Marcos Rocha', 2, 'LD'),
('palmeiras-3', 'team-palmeiras', 'Murilo', 15, 'ZAG'),
('palmeiras-4', 'team-palmeiras', 'Gustavo G?mez', 15, 'ZAG'),
('palmeiras-5', 'team-palmeiras', 'Z? Rafael', 8, 'VOL'),
('palmeiras-6', 'team-palmeiras', 'An?bal Moreno', 30, 'VOL'),
('palmeiras-7', 'team-palmeiras', 'Rony', 9, 'ATA'),
('palmeiras-8', 'team-palmeiras', 'Est?v?o', 41, 'ATA'),
('palmeiras-9', 'team-palmeiras', 'Raphael Veiga', 23, 'MEI'),
('palmeiras-10', 'team-palmeiras', 'Flaco L?pez', 19, 'ATA'),
('palmeiras-11', 'team-palmeiras', 'Jos? Manuel', 28, 'ATA'),
('bahia-1', 'team-bahia', 'Marcos Felipe', 1, 'GOL'),
('bahia-2', 'team-bahia', 'Cicinho', 2, 'LD'),
('bahia-3', 'team-bahia', 'Gabriel Xavier', 5, 'ZAG'),
('bahia-4', 'team-bahia', 'Kanu', 13, 'ZAG'),
('bahia-5', 'team-bahia', 'Ademir', 6, 'VOL'),
('bahia-6', 'team-bahia', 'Everaldo', 11, 'VOL'),
('bahia-7', 'team-bahia', 'Breno', 7, 'MEI'),
('bahia-8', 'team-bahia', 'Thaciano', 17, 'ATA'),
('bahia-9', 'team-bahia', 'Luciano Juba', 9, 'ATA'),
('bahia-10', 'team-bahia', 'Cauly', 21, 'ATA'),
('bahia-11', 'team-bahia', 'Rafael Rat?o', 22, 'ATA'),
('corinthians-1', 'team-corinthians', 'C?ssio', 12, 'GOL'),
('corinthians-2', 'team-corinthians', 'Fagner', 23, 'LD'),
('corinthians-3', 'team-corinthians', 'Gil', 3, 'ZAG'),
('corinthians-4', 'team-corinthians', 'Bruno M?ndez', 4, 'ZAG'),
('corinthians-5', 'team-corinthians', 'Raniele', 6, 'VOL'),
('corinthians-6', 'team-corinthians', 'Jos? Mart?nez', 8, 'MEI'),
('corinthians-7', 'team-corinthians', 'Yuri Alberto', 9, 'ATA'),
('corinthians-8', 'team-corinthians', 'Matheuzinho', 29, 'LD'),
('corinthians-9', 'team-corinthians', 'Pedro', 7, 'ATA'),
('corinthians-10', 'team-corinthians', 'R?ger Guedes', 10, 'MEI'),
('corinthians-11', 'team-corinthians', 'Deivid', 11, 'ATA'),
('sao-paulo-1', 'team-sao-paulo', 'Rafael', 1, 'GOL'),
('sao-paulo-2', 'team-sao-paulo', 'Auro', 2, 'LD'),
('sao-paulo-3', 'team-sao-paulo', 'Arboleda', 3, 'ZAG'),
('sao-paulo-4', 'team-sao-paulo', 'Sabino', 4, 'ZAG'),
('sao-paulo-5', 'team-sao-paulo', 'James Rodr?guez', 5, 'VOL'),
('sao-paulo-6', 'team-sao-paulo', 'Paulinho', 7, 'MEI'),
('sao-paulo-7', 'team-sao-paulo', 'Luciano', 9, 'ATA'),
('sao-paulo-8', 'team-sao-paulo', 'Alvarez', 11, 'ATA'),
('sao-paulo-9', 'team-sao-paulo', 'Wesley', 14, 'ATA'),
('sao-paulo-10', 'team-sao-paulo', 'Calleri', 18, 'ATA'),
('sao-paulo-11', 'team-sao-paulo', 'Moreira', 30, 'ATA'),
('vasco-1', 'team-vasco', 'L?o Jardim', 1, 'GOL'),
('vasco-2', 'team-vasco', 'Jo?o Victor', 2, 'LD'),
('vasco-3', 'team-vasco', 'Lucas Oliveira', 3, 'ZAG'),
('vasco-4', 'team-vasco', 'Marlon', 4, 'ZAG'),
('vasco-5', 'team-vasco', 'Zeca', 5, 'VOL'),
('vasco-6', 'team-vasco', 'Gum', 8, 'MEI'),
('vasco-7', 'team-vasco', 'Tch? Tch?', 10, 'MEI'),
('vasco-8', 'team-vasco', 'Pablo Vegetti', 9, 'ATA'),
('vasco-9', 'team-vasco', 'Rayan', 11, 'ATA'),
('vasco-10', 'team-vasco', 'Erick', 19, 'ATA'),
('vasco-11', 'team-vasco', 'Jair', 27, 'ATA');

INSERT INTO matches (id, home_team_id, away_team_id, home_score, away_score, status, starts_at) VALUES
('match-corinthians-bahia', 'team-corinthians', 'team-bahia', 1, 1, 'scheduled', '2026-09-22 20:00:00'),
('match-palmeiras-sao-paulo', 'team-palmeiras', 'team-sao-paulo', 2, 0, 'live', '2026-09-21 18:00:00'),
('match-vasco-corinthians', 'team-vasco', 'team-corinthians', 0, 2, 'finished', '2026-09-20 16:00:00'),
('match-bahia-vasco', 'team-bahia', 'team-vasco', 0, 1, 'finished', '2026-09-18 15:30:00');
